ccflags-y := -std=gnu11
obj-m += SimpleDriver.o SimpleDriverArray.o

all:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules
clean:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean
